# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 769e953f0aa7632c20e676a8c099f815e7fdc7351a5b65770a7ae98b2a50a6d603e3086e2810177abe2ff260f786d489bae92da1907b37b74a20db690198513c

test:
  secret_key_base: 52a5c130cb816549ad16e1f83f0c6ef036791d775423164a3a67f4ef1a5d04b4a966f95bac4d9fb2c97274e35255195195232ff30b1eda1e1f0fe3d21361a998

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
